backend:
  name: git-gateway
  branch: preview # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'news'
    label: 'News'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'posts' }
      - { label: 'Categories', name: 'categories', widget: 'hidden', default: 'news' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - {label: "Hidden", name: "hidden", widget: "boolean", default: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'staff'
    label: 'Staff'
    folder: '_staff/'
    create: true
    slug: '{{name}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Priority', name: 'priority', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'announcements'
    label: 'Announcements'
    folder: '_announcements/'
    create: true
    slug: '{{author}}-{{name}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'testimonials'
    label: 'Testimonials'
    folder: '_testimonials/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'gallery'
    label: 'Gallery'
    folder: '_gallery/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Short Description', name: 'body', widget: 'markdown' }